matrix:
  include:
    language: java
    jdk: oraclejdk8
    script:
      - mvn clean install -X
    language: node_js
    node_js: "v7"
    install:
      - npm install -g newman
    before_script:
      - mvn clean install -X
    script:
      - newman run cm-server/src/test/resources/postman/tests.postman_collection.json
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
  - node
env:
  - CI=""