matrix:
  include:
    language: java
      jdk: oraclejdk8
    language: node_js
    before_script:
    - node --version
    - npm --version
    - newman --version
    - cd cm-server/src/text/resources
    before_install:
    - npm install -g newman
    script:
    - mvn clean install -X
    - newman run postman/candidate-management.postman_collection.json -e postman/tests.postman_collection.json
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
  - node
env:
  - CI=""