dist: trusty
language: generic

services:
  - docker

script:
- |
  docker build -t candidate-management .
  if [ -n "$TRAVIS_TAG" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    docker tag candidate-management "$DOCKER_USERNAME/candidate-management:$TRAVIS_TAG"
    docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
  fi
