language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -u root --password="" < test/travis.sql
script:
  - mvn clean install
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
  - node
env:
  - CI=""