language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2"
  - node_modules
  - node

services:
  - mysql

before_install:
  - nvm install 8
  - npm install newman --global
  - mysql -e 'CREATE DATABASE IF NOT EXISTS candidate_management;'
  - mysql -e "GRANT ALL PRIVILEGES ON candidate_management.* To 'dev_user'@'localhost' IDENTIFIED BY 'letmein';"

script:
  - cd client
  - npm install
  - npm run build
  - cd ..

  - cp -a client/build/. server/src/main/resources/static/

  - cd server 
  - mvn clean install
  - cd ..
env:
  - CI: ""
 