matrix:
  include:
    language: java
    jdk: oraclejdk8
    script:
      - mvn clean install -X
    language: node_js
    install:
      - npm install newman
    before_script:
      - cd cm-server/src/test/resources
    script:
      - newman run postman/candidate-management.postman_collection.json -e postman/tests.postman_collection.json
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
  - node
env:
  - CI=""