server.port: 8080

# Keep the connection alive if idle for a long time (needed in production)
spring.datasource:
  testWhileIdle: true
  validationQuery: SELECT 1

# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa:
  hibernate:
    ddl-auto: ""
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# Logging level
logging.level.root: INFO

#The date when an university year starts( usually on the first of October)
ro.msg.cm.university-year-start: 10-01