available-application-users:
  users:
    -
      username: "dinam"
      password: "$2a$10$H.x7vG1.VE0MWAHoLZ26UuxVR0ebfyMLFl4NdnrwaoiwXRvMYOIAy"
      firstName: "Madalina"
      lastName: "Dina"
      email: "Madalina.Dina@msg.group"
      active: 1
    -
      username: "deacs"
      password: "$2a$10$0rl8yRRLOEMvOP8IcPVwVe8XKUmQQzoPWvuJ7ox1j57v9Uv7n6Jdm"
      firstName: "Stefania"
      lastName: "Deac"
      email: "Stefania.Deac@msg.group"
      active: 1
    -
      username: "vlasa"
      password: "$2a$10$PK6bPfBjZHlcc3ug3aYoV.RpXeqR3GhiM52DDK0C28QIjV.ihU7c2"
      firstName: "Alexandra"
      lastName: "Vlas"
      email: "Alexandra.Vlas@msg.group"
      active: 1